#!/bin/bash
# Build OpenVPN on Nexenta NCP 3.0.1
# (c) 2010 qutic development
 
# Make sure only root can run this script
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi
 
cd /usr/local/src
 
# Get dependancies
apt-get install bison flex build-essential gcc-multilib libssl-dev
 
# Install LZO-Library
wget http://www.oberhumer.com/opensource/lzo/download/lzo-2.03.tar.gz
tar xzf lzo-2.03.tar.gz
cd lzo-2.03
./configure --with-lzo-headers --with-lzo-lib
make
make install
cd ..
 
# Install tuntap
wget http://github.com/downloads/kaizawa/tuntap/tuntap.tar.gz
tar xzf tuntap.tar.gz
cd tuntap
./configure
make
make install
cd ..
 
# Install vtun
wget http://prdownloads.sourceforge.net/vtun/vtun-3.0.1.tar.gz
tar xzf vtun-3.0.1.tar.gz
cd vtun-3.0.1
./configure --with-lzo-lib=/usr/local/lib/ --with-lzo-headers=/usr/local/include/lzo --disable-shaper
make
make install
cd ..
 
# Install openvpn and patch
wget http://openvpn.net/release/openvpn-2.1.3.tar.gz
tar openvpn-2.1.3.tar.gz
cd openvpn-2.1.3
wget -O tun.c http://github.com/downloads/kaizawa/openvpn-patch/tun.c.2.1.3
./configure
make
make install
cd ..
 
# copy easy-rsa
mkdir -p /usr/share/openvpn
mkdir -p /etc/openvpn
cp -r openvpn-2.1.3/easy-rsa/2.0 /usr/share/openvpn/easy-rsa
cp -r openvpn-2.1.3/easy-rsa/2.0 /etc/openvpn/easy-rsa
 
# cleanup
rm -rf openvpn-2.1.3
rm -rf vtun-3.0.1
rm -rf tuntap
rm -rf lzo-2.03
 
# Information on how to create a smf manifest for openvpn:
# http://www.c0t0d0s0.org/archives/4147-Solaris-Features-Service-Management-Facility-Part-4-Developing-for-SMF.html
 
# Manpage for openvpn:
# man -l /usr/local/share/man/man8/openvpn.8
 
echo "OpenVPN installtion done."
echo "-------------------------"
echo "Note:"
echo "If you would like to run openvpn within a zone you need to add the tun device to this zone!"
echo "run: /usr/sbin/zonecfg -z myzone 'add device;set match=/dev/tun;end' in the global zone and"
echo "restart the zone with /usr/sbin/zlogin myzone reboot."
echo "-------------------------"
 
exit 0
